# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports: 
          - 5432:5432
        env:
          POSTGRES_USER: ectotest
          POSTGRES_PASSWORD: ectotest
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@2595a954a1d3e255e0b1746055a1f4bf719b0ac9
      with:
        elixir-version: '>=1.14' # Define the elixir version [required]
        otp-version: '>=25' # Define the OTP version [required]

    - name: Restore dependencies cache - mastery_persistence
      uses: actions/cache@v3
      with:
        path: mastery_persistence/deps
        key: ${{ runner.os }}-mixpersist-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mixpersist-

    - name: Install dependencies - mastery_persistence
      run: mix deps.get
      working-directory: mastery_persistence

    - name: Create PostGres database
      run: mix ecto.create
      env:
        MIX_ENV: test
      working-directory: mastery_persistence

    - name: Migrate PostGres database
      run: mix ecto.migrate
      env:
        MIX_ENV: test
      working-directory: mastery_persistence

    - name: Run tests - mastery_persistence
      run: mix test
      working-directory: mastery_persistence

    - name: Restore dependencies cache - mastery
      uses: actions/cache@v3
      with:
        path: mastery/deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies - mastery
      run: mix deps.get
      working-directory: mastery

    - name: Run tests - mastery
      run: mix test
      working-directory: mastery
